# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from parser import Parser
from dialog import Dialog

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 386, 558))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea_2, 0, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 386, 558))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label.setMouseTracking(False)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.refresh = QtWidgets.QAction(MainWindow)
        self.refresh.setObjectName("refresh")
        self.refreshAction = QtWidgets.QAction(MainWindow)
        self.refreshAction.setObjectName("refreshAction")
        self.leftDateAction = QtWidgets.QAction(MainWindow)
        self.leftDateAction.setObjectName("leftDateAction")
        self.rightDateAction = QtWidgets.QAction(MainWindow)
        self.rightDateAction.setObjectName("rightDateAction")
        self.menu.addAction(self.refreshAction)
        self.menu.addAction(self.leftDateAction)
        self.menu.addAction(self.rightDateAction)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "курсы валют"))
        self.menu.setTitle(_translate("MainWindow", "возможности"))
        self.refresh.setText(_translate("MainWindow", "обновить данные "))
        self.refreshAction.setText(_translate("MainWindow", "обновить данные"))
        self.leftDateAction.setText(_translate("MainWindow", "ввести дату слева"))
        self.rightDateAction.setText(_translate("MainWindow", "ввести дату справа"))


class App(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super(App, self).__init__()
        self.setupUi(MainWindow)
        self.refreshAction.triggered.connect(self.refresh_data)
        self.rightDateAction.triggered.connect(self.refreshRight)
        self.leftDateAction.triggered.connect(self.refreshLeft)


    def refresh_data(self):
        print("refershed!")
        pars = Parser()
        d = pars.get_date()
        cur = pars.get_currency()
        self.label.setText("курсы валют на " + d[0]+"\n\n")
        self.label_2.setText("курсы валют на " + d[1]+"\n\n")
        for i in cur["today"]:
            self.label.setText(self.label.text()+ " ".join(i)+" руб\n")
        for i in cur["yesterday"]:
            self.label_2.setText(self.label_2.text()+ " ".join(i)+" руб\n")

    def openDialog(self):
        dialog = QtWidgets.QDialog(self)
        resp = Dialog (dialog)
        dialog.exec()
        return resp.data

    def refreshLeft(self):
        data = self.openDialog()
        if data:
            self.label.setText("курсы валют на " + data +"\n\n")
            pars = Parser()
            cur = pars.get_currency_byDate(data)
            for i in cur:
                self.label.setText(self.label.text()+ " ".join(i)+" руб\n")
        else:
            txt = self.label.text()
            self.label.setText("операция отменена")
            QtCore.QTimer.singleShot(2000, lambda: self.label.setText(txt))
            print("abort")


    def refreshRight(self):
        data = self.openDialog()
        if data:
            self.label_2.setText("курсы валют на " + data +"\n\n")
            pars = Parser()
            cur = pars.get_currency_byDate(data)
            for i in cur:
                self.label_2.setText(self.label_2.text()+ " ".join(i)+" руб\n")
        else:
            txt = self.label_2.text()
            self.label_2.setText("операция отменена")
            QtCore.QTimer.singleShot(2000, lambda: self.label_2.setText(txt))
            print("abort")



if __name__ == "__main__":
    import sys
    window = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = App()
    MainWindow.show()
    sys.exit(window.exec_())

