# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from random import randint, choice
from pyperclip import copy


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(610, 178)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PasswordLable = QtWidgets.QLabel(self.centralwidget)
        self.PasswordLable.setGeometry(QtCore.QRect(10, 10, 591, 41))
        self.PasswordLable.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.PasswordLable.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.PasswordLable.setFrameShadow(QtWidgets.QFrame.Plain)
        self.PasswordLable.setText("")
        self.PasswordLable.setObjectName("PasswordLable")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 301, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_2.addWidget(self.checkBox_4)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_2.addWidget(self.checkBox_3)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(320, 50, 279, 71))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(320, 120, 281, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.copyButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.copyButton.setObjectName("copyButton")
        self.horizontalLayout.addWidget(self.copyButton)
        self.genButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.genButton.setObjectName("genButton")
        self.horizontalLayout.addWidget(self.genButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PasswordGenerator"))
        MainWindow.setWindowIcon(QtGui.QIcon("icon.ico"))
        self.checkBox_4.setText(_translate("MainWindow", "Uppercase letters"))
        self.checkBox.setText(_translate("MainWindow", "numbers"))
        self.checkBox_2.setText(_translate("MainWindow", "special characters"))
        self.checkBox_3.setText(_translate("MainWindow", "spacers"))
        self.label.setText(_translate("MainWindow", "length: "))
        self.lineEdit.setText(_translate("MainWindow", "16"))
        self.copyButton.setText(_translate("MainWindow", "copy"))
        self.genButton.setText(_translate("MainWindow", "generate"))


class Application(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super(Application, self).__init__()
        self.setupUi(MainWindow)
        self.func()
        self.copy()
        self.genButton.clicked.connect(self.func)
        self.copyButton.clicked.connect(self.copy)
        self.checkBox.clicked.connect(self.func)
        self.checkBox_2.clicked.connect(self.func)
        self.checkBox_3.clicked.connect(self.func)
        self.checkBox_4.clicked.connect(self.func)

    def gen(self, mode):
        spacers = ["-", '_']
        specials = ['!', '#', '$', '%', '&', '(', ')', '*', '+',
                    '.', '/', ':', ';', '=', '>', '?', '@', '[',
                    ']', '^', '`', '{', '|', '}', '~', "'", '\\']
        if mode == 'numbers':
            return randint(0, 9)
        elif mode == 'upper':
            return chr(randint(65, 90))
        elif mode == 'lower':
            return chr(randint(97, 122))
        elif mode == 'spacers':
            return choice(spacers)
        elif mode == 'specials':
            return choice(specials)

    def generate_passwords(self, length, mods, n=1):
        if n != 1:
            passwords = []
            for x in range(n):
                password = ''
                for i in range(length):
                    md = choice(mods)
                    password += str(self.gen(md))
                passwords.append(password)
            return passwords
        else:
            password = ''
            for i in range(length):
                md = choice(mods)
                password += str(self.gen(md))
            return password

    def func(self):
        modes = ["lower"]
        if self.checkBox_4.isChecked():
            modes.append("upper")
        if self.checkBox.isChecked():
            modes.append("numbers")
        if self.checkBox_2.isChecked():
            modes.append("specials")
        if self.checkBox_3.isChecked():
            modes.append("spacers")
        if self.lineEdit.text() == '':
            length = 0
        else:
            length = int(self.lineEdit.text())
        self.password = self.generate_passwords(length, modes)
        self.PasswordLable.setText(self.password)

    def copy(self):
        if self.password:
            copy(self.password)


if __name__ == "__main__":
    import sys
    window = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    app = Application()
    MainWindow.show()
    sys.exit(window.exec_())
