# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mines = QtWidgets.QLCDNumber(self.centralwidget)
        self.mines.setGeometry(QtCore.QRect(690, 10, 101, 41))
        self.mines.setDigitCount(3)
        self.mines.setObjectName("mines")
        self.time = QtWidgets.QLCDNumber(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(100, 10, 71, 41))
        self.time.setDigitCount(2)
        self.time.setObjectName("time")
        self.time_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.time_2.setGeometry(QtCore.QRect(10, 10, 71, 41))
        self.time_2.setDigitCount(2)
        self.time_2.setObjectName("time_2")
        self.dvoetoch = QtWidgets.QLabel(self.centralwidget)
        self.dvoetoch.setGeometry(QtCore.QRect(90, 0, 16, 61))
        self.dvoetoch.setObjectName("dvoetoch")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(190, 20, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(600, 10, 91, 41))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dvoetoch.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">:</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "старт"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">осталось мин :</span></p></body></html>"))
        self.menu.setTitle(_translate("MainWindow", "сложность"))
        self.action.setText(_translate("MainWindow", "легко"))
        self.action_2.setText(_translate("MainWindow", "средне"))
        self.action_3.setText(_translate("MainWindow", "сложно"))

class MyMainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, *args, **kwargs):
        super(MyMainWindow, self).__init__(*args, **kwargs)
        self.setupUi(self)
        self.difficulty = 0
        self.app()

    def app(self):
        self.action.triggered.connect(lambda: self.changedif(1))
        self.action_2.triggered.connect(lambda: self.changedif(2))
        self.action_3.triggered.connect(lambda: self.changedif(3))
        self.pushButton.clicked.connect(self.newGame)

    def newGame(self):
        pass

    def changedif(self, dif):
        self.difficulty = dif


import sys
app = QtWidgets.QApplication(sys.argv)  # A new instance of QApplication
form = MyMainWindow()
form.show()
app.exec_()
